# Generated by Django 3.2.12 on 2023-07-04 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_favoritebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritebook',
            name='book',
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='books',
            field=models.ManyToManyField(to='app.Book', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
