# Generated by Django 3.2.12 on 2023-07-05 06:44

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='size should be more than 100 MB', null=True, upload_to='customers/', verbose_name='Book Cover'),
        ),
    ]
